### ISSUE TITLE
edX was hardcoded in the cookie banner

### ISSUE THREAD

**Issue by vunguyen-dmt** [openedx/frontend-app-authn#712]
in the cookie banner can we change "edX and its members..." to "{PLATFORM_NAME} and its members..."
Is there a way to set the cookie banner off by default?

**Comment by arbrandes** [comment]
@vunguyen-dmt, this was already fixed by https://github.com/openedx/frontend-app-authn/pull/707, where you'll be able to disable the banner via `ENABLE_COOKIE_POLICY_BANNER`.

However, this will likely only make it into Olive.2.  If you want to get it before with Tutor, you can try setting the authn MFE to master and rebuild the image.

**Comment by vunguyen-dmt** [comment]
Thank you @arbrandes , how about changing the text "edX" to PLATFORM_NAME?
I should've reported this issue in cookie banner repo but I couldn't find the issue tab there.

**Comment by arbrandes** [comment]
@zainab-amir, what do you think?  Would the suggested `PLATFORM_NAME` change be acceptable?

@vunguyen-dmt, would you be able to submit a PR to implement this?

**Comment by zainab-amir** [comment]
@arbrandes I tried creating a [PR](https://github.com/openedx/frontend-component-cookie-policy-banner/pull/416) for this but the cookie banner was not created with openedX in mind. Even if I update the string, the whole architecture is edX dependent. This is the reason I went with the flag option (`ENABLE_COOKIE_POLICY_BANNER`) where the cookie banner is disabled by default.

**Comment by arbrandes** [comment]
Alright.  I guess we can close this, then.  Thanks @zainab-amir!
